//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.05.17 at 04:54:08 PM WAT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://spearheadconsult.com/nova/xml", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.spearhead.nova.model.endpoint;
